name: "Execute Org Terraform Config"
on:
  push:
    branches: [main]
    paths:
      - 0-org/*.tf*
      - 0-org/modules/*.tf*
      - .github/workflows/org-deploy.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.5.0'
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/649069422843/locations/global/workloadIdentityPools/wif-gh-pool/providers/wif-gh-provider
          service_account: org-terraform@prj-b-seed-d0b9.iam.gserviceaccount.com
      - id: 'apply_bootstrap'
        name: 'Terraform Apply - Bootstrap'
        uses: docker://gcr.io/cloud-foundation-cicd/cft/developer-tools:1.0
        with:
          entrypoint: /bin/bash
          args: -c "export GOOGLE_OAUTH_ACCESS_TOKEN=${{ steps.auth.outputs.access_token }} && cd 1-org/ && terraform init && terraform apply -var-file=org.tfvars -auto-approve"
