name: "Execute Project Factory Terraform"
on:
  push:
    branches: [main]
    paths:
      - 3-projects/*/*.tf
      - ./helper/project-deploy-workflow.sh
      - modules/single_project/*.tf*
      - .github/workflows/projects-deploy.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: gcr.io/cloud-foundation-cicd/cft/developer-tools:1.0
    permissions:
      id-token: write
      contents: read
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.5.0'
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/649069422843/locations/global/workloadIdentityPools/wif-gh-pool/providers/wif-gh-provider
          service_account: org-terraform@prj-b-seed-d0b9.iam.gserviceaccount.com
      - uses: jitterbit/get-changed-files@v1
        with:
          # Format of the steps output context.
          # Can be 'space-delimited', 'csv', or 'json'.
          # Default: 'space-delimited'
          format: ''

      - id: 'apply'
        name: 'Terraform Apply - Projects'
        run: |
          export GOOGLE_OAUTH_ACCESS_TOKEN=${{ steps.auth.outputs.access_token }}
          changed_files=${{ steps.files.outputs.all }}
          echo $changed_files
